### ISSUE TITLE
Problem with showing fa-ir language characters in keywords

### ISSUE THREAD

**Issue by pooriaanv** [madeITBelgium/SEO-Analyzer#6]
`return SEO::analyze('https://www.lahzino.ir')`  returns:
Malformed UTF-8 characters, possibly incorrectly encoded.

`dd(SEO::analyze('https://www.lahzino.ir'))` : 
`"keywords" => array:[
      b"ø" => 410
      b"ù" => 245
      b"ûœ" => 35
      b"ûœø" => 25
      b"øªø" => 23
      b"ú" => 20
      b"ûœù" => 18
      b"øªù" => 18]`

**Comment by madeITBelgium** [comment]
I will look into this asap.

**Comment by pooriaanv** [comment]
> I will look into this asap.

thanks, I checked source code, there is problem with str_word_count and strtolower functions in findKeywords method. persian or Arabic language hasn't got uppercase or lowercase characters.
mb_str_word_count instead of str_word_count

**Comment by pooriaanv** [comment]
> I will look into this asap.

thanks, I checked source code, there is a problem with str_word_count and strtolower functions in findKeywords method. Persian or Arabic language hasn't got uppercase or lowercase characters.
mb_str_word_count instead of str_word_count.

**Comment by madeITBelgium** [comment]
Thank you for your pull request.
